//
//  Solution2.swift
//  ProjectEuler
//
//  Created by Sacha DSO on 07/11/2017.
//  Copyright © 2017 sachadso. All rights reserved.
//

import Foundation

// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

struct Solution2: Solution {
    
    func run() -> Int {
        var sum = 0
        var result = 0
        var pair = (1, 2)
        while result < 4000000 {
            result = pair.0
            if result % 2 == 0 {
                sum += result
            }
            pair = (pair.1, pair.0 + pair.1)
        }
        return sum
    }
}
